### ISSUE TITLE
How much time does it take to reflect the submission changes on the leadership board?

### ISSUE THREAD

**Issue by VedikaSrivastava** [minerllabs/basalt_intro_track_2022_competition_submission_template#2]
I just made a submission with debug set to False, the evaluation was successful however the leadership board still says "Debug submission" and references my submission made yesterday.

Is there something I am missing.

**Comment by Miffyli** [comment]
Submissions take time to evaluate. Be patient and continue to check the issue page of the submission for updates!

PS: We are more responsive on the [Discord](https://discord.com/invite/BT9uegr) server :)

**Comment by VedikaSrivastava** [comment]
> Submissions take time to evaluate. Be patient and continue to check the issue page of the submission for updates!
> 
> PS: We are more responsive on the [Discord](https://discord.com/invite/BT9uegr) server :)

the issues page says "evaluation successful" but i dont see it reflected on the leadership board.

I'll join the discord group. thank you!
